pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/username/messaging-app.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                echo 'Setting up Python environment...'
                sh '''
                    python3 -m venv ${VENV_DIR}
                    source ${VENV_DIR}/bin/activate
                    pip3 install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests with Pytest') {
            steps {
                echo 'Running tests...'
                sh '''
                    source ${VENV_DIR}/bin/activate
                    pytest --maxfail=5 --disable-warnings -q --junitxml=pytest_report.xml
                '''
            }
        }

        stage('Archive Test Reports') {
            steps {
                echo 'Archiving test results...'
                junit 'pytest_report.xml'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up environment...'
            sh 'rm -rf ${VENV_DIR}'
        }
    }
}
