pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-token', 
                    url: 'https://github.com/Happiness7230/alx-backend-python.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh '''
                python3 -m venv ${VENV_DIR}
                source ${VENV_DIR}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests with Pytest') {
            steps {
                sh '''
                source ${VENV_DIR}/bin/activate
                cd messaging_app
                pytest --maxfail=1 --disable-warnings --junitxml=test-results.xml -v
                '''
            }
        }

        stage('Generate Report') {
            steps {
                junit 'messaging_app/test-results.xml'
            }
        }
    }

    post {
        always {
            echo "Cleaning up environment..."
            sh 'rm -rf ${VENV_DIR}'
        }
    }
}

