apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging
  template:
    metadata:
      labels:
        app: django-messaging
    spec:
      containers:
        - name: django-messaging-container
          image: messaging_app:latest     # 👈 local image built inside Minikube
          imagePullPolicy: Never          # 👈 ensures Minikube uses your local build
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: messaging_app.settings
---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  selector:
    app: django-messaging
  ports:
    - protocol: TCP
      port: 8000           # 👈 service port
      targetPort: 8000     # 👈 container port
  type: ClusterIP          # 👈 internal service
